// Course
export const GET_COURSE_SPEC_SUCCESS = 'GET_COURSE_SPEC_SUCCESS';
export const GET_COURSE_SPEC_FAILURE = 'GET_COURSE_SPEC_FAILURE';

export const GET_HUBS_SUCCESS = 'GET_HUBS_SUCCESS';
export const GET_HUBS_FAILURE = 'GET_HUBS_FAILURE';
