// General
export const SET_PAGE_STYLE = 'SET_PAGE_STYLE'

// Auth
export const SHOW_AUTH = 'SHOW_AUTH'
export const DISMISS_AUTH = 'DISMISS_AUTH'

export const CHECK_AUTH_SUCCESS = 'CHECK_AUTH_SUCCESS'
export const CHECK_AUTH_FAILURE = 'CHECK_AUTH_FAILURE'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

// Course
export const GET_SCHEDULE_SUCCESS = 'GET_SCHEDULE_SUCCESS'
export const GET_SCHEDULE_FAILURE = 'GET_SCHEDULE_FAILURE'

export const GET_HUBS_SUCCESS = 'GET_HUBS_SUCCESS'
export const GET_HUBS_FAILURE = 'GET_HUBS_FAILURE'

export const GET_SPEC_SUCCESS = 'GET_SPEC_SUCCESS'
export const GET_SPEC_FAILURE = 'GET_SPEC_FAILURE'

export const SET_CURRENT_CLASS = 'SET_CURRENT_CLASS'
export const SET_COURSE_LANG = 'SET_COURSE_LANG'

// Conversation
export const EXPAND_CONVERSATION = 'EXPAND_CONVERSATION'
export const COLLAPSE_CONVERSATION = 'COLLAPSE_CONVERSATION'

// Messages
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS'
export const GET_MESSAGES_FAILURE = 'GET_MESSAGES_FAILURE'

export const SEND_MESSAGE = 'SEND_MESSAGE'

export const PUSH_SEGMENT_MESSAGE = 'PUSH_SEGMENT_MESSAGE'
export const SET_SEGMENT_MESSAGES = 'SET_SEGMENT_MESSAGES'
export const SET_SUBSCRIBED_TO = 'SET_SUBSCRIBED_TO'

export const SET_REPLYING_TO = 'SET_REPLYING_TO'

export const SET_ACTIVE_SEGMENT = 'SET_ACTIVE_SEGMENT'
export const SET_PEEK_SEGMENT = 'SET_PEEK_SEGMENT'

// Subtitles
export const GET_SUBTITLES_SUCCESS = 'GET_SUBTITLES_SUCCESS'
export const GET_SUBTITLES_FAILURE = 'GET_SUBTITLES_FAILURE'

// Visualisation
export const GET_VISUALISATION_SUCCESS = 'GET_VISUALISATION_SUCCESS'
export const GET_VISUALISATION_FAILURE = 'GET_VISUALISATION_FAILURE'

// Question Modal
export const SHOW_QUESTION_MODAL = 'SHOW_QUESTION_MODAL'
export const DISMISS_QUESTION_MODAL = 'DISMISS_QUESTION_MODAL'

// Info Modal
export const SHOW_INFO_MODAL = 'SHOW_INFO_MODAL'
export const DISMISS_INFO_MODAL = 'DISMISS_INFO_MODAL'

// Navigation
export const SET_NAV_STATE = 'SET_NAV_STATE'
export const TOGGLE_LEFT_DRAWER = 'TOGGLE_LEFT_DRAWER'
export const TOGGLE_RIGHT_DRAWER = 'TOGGLE_RIGHT_DRAWER'

export const DISMISS_DRAWERS = 'DISMISS_DRAWERS'
export const DISMISS_LEFT_DRAWER = 'DISMISS_LEFT_DRAWER'
export const DISMISS_RIGHT_DRAWER = 'DISMISS_RIGHT_DRAWER'

// Profile
export const DISMISS_PROFILE_ACTION = 'DISMISS_PROFILE_ACTION'

// Action Panel
export const SHOW_MEDIA = 'SHOW_MEDIA'
export const HIDE_MEDIA = 'HIDE_MEDIA'

// Media
export const SET_LIGHTBOX_MEDIA = 'SET_LIGHTBOX_MEDIA'
export const PLAY_MEDIA = 'PLAY_MEDIA'
export const PAUSE_MEDIA = 'PAUSE_MEDIA'
export const SET_SEEK_POSITION = 'SET_SEEK_POSITION'

// Scroll Position
export const SAVE_SCROLL_POSITION = 'SAVE_SCROLL_POSITION'
export const RESET_SCROLL_POINTS = 'RESET_SCROLL_POINTS'
export const SET_SCROLL_POINT = 'SET_SCROLL_POINT'
export const SET_CURRENT_SECTION = 'SET_CURRENT_SECTION'