version: 2
general:
  branches:
    only:
     - master
jobs:
  build:
    docker:
      - image: node:7.4.0
    working_directory: ~/connectedacademy
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm run build
      - add_ssh_keys
      - run: git config --global user.name "CircleCI"
      - run: git config --global user.email "info@connectedacademy.io"
      - run: git add docs
      - run: git commit -am"[skip CI] AUTOBUILD"
      - run: git push -u -f origin master

  test:
    docker:
      - image: node:7.4.0
    working_directory: ~/connectedacademy
    steps:
      - checkout
      # Download the browserstack binary file
      - run: wget "https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip"
      # Unzip the browserstack binary file
      - run: apt-get update && apt-get install unzip
      - run: unzip BrowserStackLocal-linux-x64.zip
      # Run the file with your access key
      - run:
          name: Browserstack Local
          command: ./BrowserStackLocal $BROWSERSTACK_KEY
          background: true
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm i --silent && npm i -g serve
      - run: npm run build
      - run: 
          name: Server
          command: serve docs
          background: true
      - run: node_modules/.bin/wdio

    # docker:
    #   - image: node:7.4.0
    # working_directory: ~/connectedacademy
    # steps:
    #   - checkout
    #   - restore_cache:
    #       key: dependency-cache-{{ checksum "package.json" }}
    #   - run: npm i --silent
    #   - run: npm i -g --silent serve
    #   - run: npm run build && serve docs && wdio

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test