version: 2
general:
  branches:
    only:
     - master
jobs:
  build:
    docker:
      - image: node:7.4.0
    working_directory: ~/connectedacademy
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm run build
      - add_ssh_keys
      - run: git config --global user.name "CircleCI"
      - run: git config --global user.email "info@connectedacademy.io"
      - run: git add docs
      - run: git commit -am"[skip CI] AUTOBUILD"
      - run: git push -u -f origin master
